package application

import (
	"context"
	"fmt"

	"github.com/marconneves/coolify-sdk-go/client"
)

// CreateDockerImageDTO represents the data required to create an application
// based on a prebuilt Docker image (e.g. one hosted on GCP Artifact Registry).
type CreateDockerImageDTO struct {
	ProjectUUID             string  `json:"project_uuid"`
	ServerUUID              string  `json:"server_uuid"`
	EnvironmentName         string  `json:"environment_name,omitempty"`
	EnvironmentUUID         string  `json:"environment_uuid,omitempty"`
	DockerRegistryImageName string  `json:"docker_registry_image_name"`
	PortsExposes            string  `json:"ports_exposes"`
	DockerRegistryImageTag  *string `json:"docker_registry_image_tag,omitempty"`
	DestinationUUID         *string `json:"destination_uuid,omitempty"`
	Name                    *string `json:"name,omitempty"`
	Description             *string `json:"description,omitempty"`
	Domains                 *string `json:"domains,omitempty"`
	PortsMappings           *string `json:"ports_mappings,omitempty"`

	HealthCheckEnabled      *bool   `json:"health_check_enabled,omitempty"`
	HealthCheckPath         *string `json:"health_check_path,omitempty"`
	HealthCheckPort         *string `json:"health_check_port,omitempty"`
	HealthCheckHost         *string `json:"health_check_host,omitempty"`
	HealthCheckMethod       *string `json:"health_check_method,omitempty"`
	HealthCheckReturnCode   *int    `json:"health_check_return_code,omitempty"`
	HealthCheckScheme       *string `json:"health_check_scheme,omitempty"`
	HealthCheckResponseText *string `json:"health_check_response_text,omitempty"`
	HealthCheckInterval     *int    `json:"health_check_interval,omitempty"`
	HealthCheckTimeout      *int    `json:"health_check_timeout,omitempty"`
	HealthCheckRetries      *int    `json:"health_check_retries,omitempty"`
	HealthCheckStartPeriod  *int    `json:"health_check_start_period,omitempty"`

	LimitsMemory            *string `json:"limits_memory,omitempty"`
	LimitsMemorySwap        *string `json:"limits_memory_swap,omitempty"`
	LimitsMemorySwappiness  *int    `json:"limits_memory_swappiness,omitempty"`
	LimitsMemoryReservation *string `json:"limits_memory_reservation,omitempty"`
	LimitsCpus              *string `json:"limits_cpus,omitempty"`
	LimitsCpuset            *string `json:"limits_cpuset,omitempty"`
	LimitsCPUShares         *int    `json:"limits_cpu_shares,omitempty"`

	CustomLabels                   *string `json:"custom_labels,omitempty"`
	CustomDockerRunOptions         *string `json:"custom_docker_run_options,omitempty"`
	PostDeploymentCommand          *string `json:"post_deployment_command,omitempty"`
	PostDeploymentCommandContainer *string `json:"post_deployment_command_container,omitempty"`
	PreDeploymentCommand           *string `json:"pre_deployment_command,omitempty"`
	PreDeploymentCommandContainer  *string `json:"pre_deployment_command_container,omitempty"`

	ManualWebhookSecretGithub    *string `json:"manual_webhook_secret_github,omitempty"`
	ManualWebhookSecretGitlab    *string `json:"manual_webhook_secret_gitlab,omitempty"`
	ManualWebhookSecretBitbucket *string `json:"manual_webhook_secret_bitbucket,omitempty"`
	ManualWebhookSecretGitea     *string `json:"manual_webhook_secret_gitea,omitempty"`

	Redirect                      *string `json:"redirect,omitempty"`
	InstantDeploy                 *bool   `json:"instant_deploy,omitempty"`
	IsForceHTTPSEnabled           *bool   `json:"is_force_https_enabled,omitempty"`
	UseBuildServer                *bool   `json:"use_build_server,omitempty"`
	IsHTTPBasicAuthEnabled        *bool   `json:"is_http_basic_auth_enabled,omitempty"`
	HTTPBasicAuthUsername         *string `json:"http_basic_auth_username,omitempty"`
	HTTPBasicAuthPassword         *string `json:"http_basic_auth_password,omitempty"`
	ConnectToDockerNetwork        *bool   `json:"connect_to_docker_network,omitempty"`
	ForceDomainOverride           *bool   `json:"force_domain_override,omitempty"`
	AutogenerateDomain            *bool   `json:"autogenerate_domain,omitempty"`
	IsContainerLabelEscapeEnabled *bool   `json:"is_container_label_escape_enabled,omitempty"`
}

// CreateDockerImageResponse is the response returned when creating a Docker image
// application.
type CreateDockerImageResponse struct {
	UUID string `json:"uuid"`
}

// CreateDockerImage creates a new application from a prebuilt Docker image.
func (a *ApplicationInstance) CreateDockerImage(ctx context.Context, data *CreateDockerImageDTO) (*string, error) {
	buf, err := client.EncodeRequest(data)
	if err != nil {
		return nil, fmt.Errorf("failed to encode request: %w", err)
	}

	body, err := a.client.HttpRequestWithContext(ctx, "applications/dockerimage", "POST", *buf)
	if err != nil {
		return nil, fmt.Errorf("failed to create docker image application: %w", err)
	}

	response, err := client.DecodeResponse(body, &CreateDockerImageResponse{})
	if err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &response.UUID, nil
}
